image: docker.fslab.de/lschau2s/debian-zfs-installer

stages:
  - build

build:
  stage: build
  artifacts:
    paths:
      - debian-custom.iso
    expire_in: 2h
    expose_as: 'Live ISO'
  script:
    - ./build.sh
